// Small hand-written training set (English + romanized Hinglish) for NaiveBayesClassifier.
// Written by the Voino author team for this prototype; not a public benchmark.
const kTrainingSentences = <List<String>>[
  ['action', "Kal tak report bhejni hai."],
  ['action', "Hume client ko proposal submit karna hai."],
  ['action', "Tum slides ready kar do by Friday."],
  ['action', "Mujhe assignment complete karna hai."],
  ['action', "Please send the invoice to finance today."],
  ['action', "We need to finish the deck before the meeting."],
  ['action', "Rahul ko bolna hai ki code review kare."],
  ['action', "Next week tak design final karna padega."],
  ['action', "Don't forget to book the room for Monday."],
  ['action', "Isko kal subah tak update karna hoga."],
  ['action', "I will email the notes to everyone."],
  ['action', "Aap log homework submit kar dena."],
  ['action', "Someone should follow up with the vendor."],
  ['action', "Yaad rakhna ki form bharna hai."],
  ['action', "Deadline Friday hai, isliye jaldi karo."],
  ['action', "Mujhe doctor ko call karna hai."],
  ['action', "Remember to review the pull request."],
  ['action', "Sabko attendance sheet bharni hai."],
  ['action', "Hume budget prepare karna chahiye."],
  ['action', "You have to submit the lab record tomorrow."],
  ['action', "Priya ko ye file bhej do please."],
  ['action', "Let's schedule a follow up call next week."],
  ['action', "Kal tak sab log feedback bhej dena."],
  ['action', "Hame testing complete karni hogi."],
  ['action', "Make sure you update the spreadsheet."],
  ['action', "Ye task Monday tak close karna hai."],
  ['action', "I need to prepare the presentation tonight."],
  ['action', "Mail bhejna mat bhoolna."],
  ['action', "Assignment ka deadline kal hai, submit kar dena."],
  ['action', "Team ko reminder bhejna padega."],
  ['decision', "Hum pricing pe tay hua ki 999 rakhenge."],
  ['decision', "We decided to go with the second option."],
  ['decision', "Final hai ki launch next month hoga."],
  ['decision', "Toh decide kiya ki Flutter hi use karenge."],
  ['decision', "We agreed to move the meeting to Thursday."],
  ['decision', "Tay hua hai ki hum free plan rakhenge."],
  ['decision', "The final decision is to ship on Friday."],
  ['decision', "Hum Hinglish support pehle karenge, yeh fix hai."],
  ['decision', "We will go with the cheaper vendor."],
  ['decision', "Sabne agree kiya ki weekly sync hoga."],
  ['decision', "Okay so decided, we are skipping the beta."],
  ['decision', "Hum Android pe focus karenge, iOS baad mein."],
  ['decision', "It's settled, the budget stays the same."],
  ['decision', "Faisla ho gaya ki hum office se kaam karenge."],
  ['decision', "We'll go with Firebase for login."],
  ['decision', "Agreed, hum Monday ko release karenge."],
  ['decision', "Decision yeh hai ki hum paid tier nahi rakhenge."],
  ['decision', "We are going ahead with the new design."],
  ['decision', "Toh final kar diya, demo Wednesday ko hoga."],
  ['decision', "Everyone agreed to use the shared drive."],
  ['question', "Kya deadline kal hai?"],
  ['question', "Who is going to present this?"],
  ['question', "Ye kaise kaam karta hai?"],
  ['question', "When does the client arrive?"],
  ['question', "Kitna budget bacha hai abhi?"],
  ['question', "Kya hum Friday ko meet kar sakte hain?"],
  ['question', "How much will this cost us?"],
  ['question', "Kaun is task ko lega?"],
  ['question', "Is the API ready yet?"],
  ['question', "Kab tak ye khatam hoga?"],
  ['question', "Kya aap mujhe slides bhej sakte ho?"],
  ['question', "Where should we host the app?"],
  ['question', "Isme problem kya hai?"],
  ['question', "Can we push the date by a week?"],
  ['question', "Meeting kahan hai aaj?"],
  ['question', "What did the professor say about the exam?"],
  ['question', "Aapko kya lagta hai, ye sahi hai?"],
  ['question', "Why is the build failing?"],
  ['question', "Kitne log aa rahe hain kal?"],
  ['question', "Kya ye feature free rahega?"],
  ['background', "Aaj mausam bahut accha tha."],
  ['background', "The database has three tables."],
  ['background', "Photosynthesis happens in the chloroplast."],
  ['background', "Pichli baar humne client se baat ki thi."],
  ['background', "Yeh app lecture ko notes mein badalta hai."],
  ['background', "The market grew by ten percent last year."],
  ['background', "Mera din bahut busy raha aaj."],
  ['background', "Server ka response time kaafi slow tha."],
  ['background', "Humare paas teen engineers hain team mein."],
  ['background', "The professor explained the second law of thermodynamics."],
  ['background', "Pehle yeh system purane code pe chalta tha."],
  ['background', "Last quarter revenue was around two crore."],
  ['background', "Isme mitochondria energy banata hai."],
  ['background', "Yeh meeting kaafi lambi thi."],
  ['background', "The client seemed happy with the demo."],
  ['background', "Delhi mein traffic bahut zyada hota hai."],
  ['background', "Python is a popular programming language."],
  ['background', "Humne pehle bhi aisa try kiya tha."],
  ['background', "Netflix pe ek nayi series aayi hai."],
  ['background', "The office is closed on Sunday."],
  ['background', "Ye cheez mujhe pasand aayi."],
  ['background', "Interest rates went up this month."],
  ['background', "Woh kal late aaya tha."],
  ['background', "Cell membrane controls what enters the cell."],
  ['background', "Hamari company 2019 mein shuru hui thi."],
];
